---
upstream_package_name: goose
downstream_package_name: goose
upstream_project_url: https://github.com/block/goose

specfile_path: goose.spec

srpm_build_deps:
  - cargo
  - git
  - openssl-devel

actions:
  # The last setp here is required by Packit to return the archive name
  # https://packit.dev/docs/configuration/actions#create-archive
  create-archive:
    - bash -c "./generate-vendor-tarball.sh"
    - bash -c "ls -1 goose*.tar.xz"
  # We fix the first source of the specfile because packit just understands
  # that Source should be our create-archive output. That's simply not right
  # and it's easier to just sed it out and fix in the fix-spec-file
  fix-spec-file:
    - sed -Ei 's|^(Source:[[:space:]]+)goose-[0-9]+(\.[0-9]+)*-vendor\.tar\.xz|\1%{url}/archive/v%{version}/%{name}-%{version}.tar.gz|' goose.spec

_:
  disable_checks: &disable_checks
    without_opts:
      - check

  pr_targets: &pr_targets
    fedora-43-x86_64: *disable_checks
    fedora-44-x86_64: *disable_checks
    fedora-rawhide-x86_64: *disable_checks
    epel-9-x86_64: *disable_checks
    epel-10-x86_64: *disable_checks
    rhel-9-x86_64: *disable_checks
    rhel-10-x86_64: *disable_checks

  targets: &targets
    <<: *pr_targets
    fedora-43-aarch64: *disable_checks
    fedora-43-ppc64le: *disable_checks
    fedora-43-s390x: *disable_checks

    fedora-44-aarch64: *disable_checks
    fedora-44-ppc64le: *disable_checks
    fedora-44-s390x: *disable_checks

    fedora-rawhide-aarch64: *disable_checks
    fedora-rawhide-ppc64le: *disable_checks
    fedora-rawhide-s390x: *disable_checks

    epel-9-aarch64: *disable_checks
    epel-9-ppc64le: *disable_checks
    epel-9-s390x: *disable_checks

    epel-10-aarch64: *disable_checks
    epel-10-ppc64le: *disable_checks
    epel-10-s390x: *disable_checks

    rhel-9-aarch64: *disable_checks
    rhel-9-s390x: *disable_checks

    rhel-10-aarch64: *disable_checks
    rhel-10-s390x: *disable_checks
    rhel-10-ppc64le: *disable_checks

jobs:
  - job: copr_build
    trigger: pull_request
    owner: "@rhel-lightspeed"
    project: goose
    # Goose builds usually take a long time to finish, so we set it to 5h, just
    # in case.
    timeout: 36000
    targets: *pr_targets


  # Build on new commit to main branch
  - job: copr_build
    trigger: commit
    owner: "@rhel-lightspeed"
    project: goose
    # Goose builds usually take a long time to finish, so we set it to 5h, just
    # in case.
    timeout: 36000
    targets: *targets
